ecs_deploy

diff --git a/.github/workflows/aws_deploy.yml b/.github/workflows/aws_deploy.yml
--- a/.github/workflows/aws_deploy.yml
+++ b/.github/workflows/aws_deploy.yml
@@ -1,11 +1,12 @@
 name: Deploy to Amazon ECS
 
+
 on:
   push:
     branches:
-   
       - main
- jobs:
+
+jobs:
   build-and-test:
     runs-on: ubuntu-latest
 
@@ -33,4 +34,9 @@ on:
         run: |
           docker run -d -p 5000:5000 --name final-python-container ${{ secrets.DOCKER_USERNAME }}/final-python:latest
 
-      
+      - name: Test the container
+        run: |
+          sleep 10 
+          curl --fail http://localhost:5000/api/doc || (echo "Container test failed!" && exit 1)
+
+     
